### PR TITLE
Rename lumail2 to lumail

### PR DESCRIPTION
**Pull request by fischerling**
I changed every occurence of lumail2 in the text and changes every filename in the source tree.

`make` and `make install` worked flawless. And short usage discovered no obvious error.

**THIS BREAKES EVERY LUMAIL SETUP OUT THERE.** How should we handle this ?

### CODE REVIEW

**Comment by skx** [comment]
I appreciate the work, but I think, as per comments on #307 that the starting point would be to have code that would work with both the current _and_ the proposed locations, rather than an insta-rename.

I'd also not commit any change here until the documentation were done first.  Just for clarity.  Since more people find the code via github than the website, so people should expect the documentation to be accurate and current.

On that basis I'd close this, for the moment.  Although once again I appreciate your  contributions in general, and this specific one - I need to get this done, but this is a little too soon, and not quite what I had in mind for the start.

**Comment by fischerling** [comment]
What documentation changes have you in mind ?
I could add some code to handle the old files like you mentioned in #307. Should I ?

**Comment by skx** [comment]
I have some specific changes in mind, but it'd take a while to write them down.  I'd probably suggest you give me a week, and if I've not made significant process by then you'd be welcome to submit something - if that's not too offputting?

**Comment by fischerling** [comment]
No problem.
I was bored and wanted to do something usefull :D

**Pull request closed without merging**
